# Generated by Django 3.2.8 on 2021-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('occurrence', models.CharField(db_column='occurence', max_length=1000)),
                ('try_resolve_example', models.CharField(db_column='try_resolve_example', max_length=1000)),
                ('expiration_date', models.DateTimeField(db_column='expiration_date')),
                ('requisite_customer', models.CharField(db_column='requisite_customer', max_length=1000)),
            ],
        ),
    ]
