# Generated by Django 3.2.8 on 2021-12-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211203_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='inn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='startup',
            name='ur_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
