# Generated by Django 3.2.8 on 2021-12-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211203_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children_cats',
            field=models.ManyToManyField(related_name='children_categories', to='main.Category'),
        ),
    ]
