# Generated by Django 3.2.8 on 2021-12-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_children_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='product_benefit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='children_cats',
            field=models.ManyToManyField(blank=True, related_name='children_categories', to='main.Category'),
        ),
    ]
