# Generated by Django 3.2.8 on 2021-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211203_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='startup',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='startups',
            field=models.ManyToManyField(blank=True, related_name='user_startups', to='main.Startup'),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
