# Generated by Django 3.2.8 on 2021-12-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_startup_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
