# Generated by Django 3.2.8 on 2021-12-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_startup_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='startup_comment', to='main.comment'),
        ),
        migrations.RemoveField(
            model_name='startup',
            name='pending_pilots',
        ),
        migrations.AddField(
            model_name='startup',
            name='pending_pilots',
            field=models.ManyToManyField(blank=True, related_name='startup_pending_pilots', to='main.Pilot'),
        ),
        migrations.RemoveField(
            model_name='startup',
            name='pilots',
        ),
        migrations.AddField(
            model_name='startup',
            name='pilots',
            field=models.ManyToManyField(blank=True, related_name='startup_pilots', to='main.Pilot'),
        ),
    ]
