# Generated by Django 3.2.8 on 2021-12-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211203_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
