# Generated by Django 3.2.8 on 2021-12-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211204_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
